import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Inter, Montserrat, Bakbak_One } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const montserrat = Montserrat({
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const bakbak_one = Bakbak_One({
  weight: ["400"],
  variable: "--font-backbak-one",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Elevano",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bakbak_one.variable} ${montserrat.variable}`}>
        <>
          {/* Landing page Hero Section */}
          <header className="heroBackground py-2">
            {/* Nav Section */}
            <div className="px-[150px] py-4 flex items-center justify-between">
              {/* Logo */}
              <div className="">
                <Image src="/logo.svg" alt="logo" width="147" height="52" />
              </div>

              {/* Nav List */}
              <nav className="w-2/6">
                <ul className="flex w-full justify-between">
                  <li>
                    <Link href="#">Home</Link>
                  </li>
                  <li>
                    <Link href="#">Our Services</Link>
                  </li>
                  <li>
                    <Link href="#">Our Work</Link>
                  </li>
                  <li>
                    <Link href="#">About Us</Link>
                  </li>
                </ul>
              </nav>

              {/* Request Button */}
              <div className="">
                <button className="py-3 px-4 border-white border-[1px] rounded-[4px]">
                  Request a Quote
                </button>
              </div>
            </div>
            {/* Horizontal Line */}
            <hr className="h-px bg-[#44406D] border-0 dark:bg-[#44406D]"></hr>

            {/* Hero Title Section */}
            <div className="mx-40 my-16">
              <h2 className="w-[800px] font-normal text-5xl text-[#e6e6e6] font-bakbakOne leading-normal">
                Crafting Excellence: Create the Best Digital Products with Us
              </h2>

              <p className="font-semibold font-montserrat text-2xl text-[#9593A8] py-14">
                Your Trusted Partner in Crafting Exceptional Experiences
              </p>
            </div>
          </header>

          {children}

          {/* Footer */}
          <footer className="footer py-16 px-96 flex flex-col justify-center items-center gap-[76px]">
            <h6 className="text-white font-montserrat font-semibold text-5xl leading-[56px] text-center">
              Have A Project In Mind? Let’s Get To Work With Us.
            </h6>

            <button className="w-2/6 py-3 px-4 border-white border-[1px] rounded-[4px]">
              Contact Us
            </button>
          </footer>
        </>
      </body>
    </html>
  );
}
